### ISSUE TITLE
Falscher Datentyp

### ISSUE THREAD

**Issue by valentinmanthei** [billbee-de/billbee-php-sdk#2]
Danke erstmal für das schöne Package, erleichtert die Arbeit mit der API wirklich sehr!

Ich habe hier folgenden Fehler (Stacktrace gekürzt und sensible Daten entfernt):
`(1/1) TypeMismatchException
Wrong Type. Expected int got string
in ObjectMapper.php (line 144)
at ObjectMapper->mapDataToObject(array('Id' => '123534', 'Name' => 'Farbe', 'Value' => 'xxx', 'Price' => 0), 'BillbeeDe\\BillbeeAPI\\Model\\OrderItemAttribute')
in ObjectMapper.php (line 246)
at ObjectMapper->mapDataToObject(array('TransactionId' => '393663424723', ...))`

Habe als Quickfix in OrderItemAttribute die Annotation auf string geändert: `@JsonField(name="Id", type="string")`. Vielleicht könnt ihr das ja mal ansehen...

**Comment by Devtronic** [comment]
Danke :-)
Du musst Id einfach zu nem int casten also (int)$variableMitId

**Comment by valentinmanthei** [comment]
Naja, das ist schon klar. Allerdings bastle ja aber nicht ich den Request zusammen, sondern da kommt offensichtlich von der API ein string statt int zurück.

**Comment by Devtronic** [comment]
Ach so, na das ist natürlich was anderes. Schaue ich mir an.

**Comment by Devtronic** [comment]
@valentinmanthei gefixt in v1.0.1
