### ISSUE TITLE
Payment Method

### ISSUE THREAD

**Issue by dinhbang** [billbee-de/billbee-php-sdk#81]
Hello,

I am doing sync order from Amazon via BillBee API. 
The order is return paymentMethod is integer. Example It is return 61. How I can know real name payment method example credit card or Amazon Pay....

Regards,
Bang.

**Comment by devtronic** [comment]
Hi, take a look inside this file: https://github.com/billbeeio/billbee-php-sdk/blob/master/src/Type/PaymentType.php

Detecting the underlying payment method is not possible.

**Comment by dinhbang** [comment]
> Hi, take a look inside this file: https://github.com/billbeeio/billbee-php-sdk/blob/master/src/Type/PaymentType.php
> 
> Detecting the underlying payment method is not possible.

Yes, thank you so much!
